# Generated by Django 4.0.4 on 2022-05-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento AAAA-MM-DD')),
                ('edad', models.IntegerField(max_length=3, verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=16, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
    ]
