# Generated by Django 4.0.4 on 2022-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familias',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
