# Generated by Django 4.0.4 on 2022-05-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_alter_familias_edad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familias',
            new_name='Familia',
        ),
    ]
