# Generated by Django 4.0.4 on 2022-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_rename_familias_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
