# Generated by Django 4.0.4 on 2022-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='familia',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='familia',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
