# Generated by Django 4.0.4 on 2022-05-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_alter_familia_apellido_alter_familia_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='apellido',
            field=models.CharField(max_length=45, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='direccion',
            field=models.CharField(max_length=60, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='telefono',
            field=models.CharField(max_length=16, verbose_name='Teléfono'),
        ),
    ]
